### ISSUE TITLE
Uploaded files are set to private

### ISSUE THREAD

**Issue by abm-devmonk-purple** [abhayagiri/abhayagiri-website#114]
When uploading a file via the admin/File Manager on staging or production, the resulting file is not publicly visible (i.e., set to private). When viewing or downloading the file, an error is generated. For example:

![image](https://user-images.githubusercontent.com/18488288/62784954-6d0c3500-ba74-11e9-8677-86f49d10c775.png)

**Comment by abm-devmonk-purple** [comment]
This seems to be due to a misconfiguration or bug in the filesystem driver for Digital Ocean Spaces.

**Comment by abm-devmonk-purple** [comment]
A better fix might be a configuration setting. See:

https://www.digitalocean.com/community/questions/how-to-set-permission-of-all-files-in-a-bucket-as-public-on-every-upload

**Comment by coderintherye** [comment]
@abm-devmonk-purple looks like you found a good band-aid by running the recursive s3cmd to set everything public. I found some discussion here that may be of interest: https://www.digitalocean.com/community/questions/how-to-make-my-spaces-public?answer=50832 
Though, searching through the website code I didn't offhand seem to find where the code is that actually handles the upload (in order to see if it is setting an ACL)

**Comment by abm-devmonk-purple** [comment]
@coderintherye In doesn't appear that there is any. The current fix (https://github.com/abhayagiri/abhayagiri-website/commit/c936baf6226e409a104bddeec5b2e13a1de764a8#diff-e8370a3ff0ac2b1f170f804096fded3aR47) is brittle against upstream changes.

**Comment by abm-devmonk-purple** [comment]
I think this is working for now.
